runs:
  - name: "Qwen3-32B-Q4_K_M-10k"
    description: "10240 context, 17-20t/s, gpu only, top quality"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m Qwen3-32B-Q4_K_M.gguf -ngl 99  -c 10240 --flash-attn --host 0.0.0.0"
  - name: "Qwen3-32B-Q4_K_M-32k"
    description: "32768 context, 5-7t/s, gpu only, top quality, the biggest context"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m Qwen3-32B-Q4_K_M.gguf -ngl 52  -c 32768 --flash-attn --host 0.0.0.0"
  - name: "Qwen3-30b-A3B-Q5_K_L-10k"
    description: "10240 context, 80t/s, top speed"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m Qwen_Qwen3-30B-A3B-Q5_K_L.gguf -ngl 99 -c 10240 --flash-attn --host 0.0.0.0"
  - name: "Qwen3-30b-A3B-Q5_K_L-32k"
    description: "32768 context, 30t/s, cpu partially, the fastest 32k context"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m Qwen_Qwen3-30B-A3B-Q5_K_L.gguf -ngl 43 -c 32768 --flash-attn --host 0.0.0.0"
  - name: "gemma3-27b-it-qat-Q5_K_XL-8k"
    description: "8192 context, 8-10t/s, cpu partially"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m gemma3-27/gemma-3-27b-it-qat-UD-Q5_K_XL.gguf -ngl 58 -c 8192 --flash-attn --host 0.0.0.0"
  - name: "gemma3-27b-it-qat-Q5_K_XL-2k"
    description: "2048 context, 16-20t/s, gpu onlu"
    cmd: "cd /home/aleksandr/repo/gguf/ && ../llama.cpp/build/bin/llama-server -m gemma3-27/gemma-3-27b-it-qat-UD-Q5_K_XL.gguf -ngl 99 -c 2048 --flash-attn --host 0.0.0.0"
